config/routes.rb
Rails.application.routes.draw do

  resources :teams
  root 'teams#index'

  get 'seasons' => 'seasons#index', as: :seasons
  get 'rounds/show/:id' => 'rounds#show', as: :show_round
  get 'rounds/index'
  get 'seasons/classification' => 'seasons#index_classification', as: :classification
  get 'season/new' => 'seasons#new', as: :new_season

  delete 'teams/:id' => 'teams#destroy', as: :teams_destroy
  post 'active' => 'seasons#update', as: 'post_active'
  patch 'match_results/:id' => 'match_results#update'
  patch '/' => 'teams#update'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :round, :dependent => :destroy
  has_many :match_results
  default_scope -> { order(created_at: :asc) }
end

app/models/match_result.rb
class MatchResult < ActiveRecord::Base
  belongs_to :team, :dependent => :destroy
  belongs_to :match, :dependent => :destroy
end

app/models/round.rb
class Round < ActiveRecord::Base
  has_many :matches
  validates :status, inclusion: { in: ['closed', 'open', 'inaccessible'] }
  default_scope { order('created_at ASC') }

  scope :active_rounds, -> { where(status: 'open' || 'inaccessible') }
end

app/models/season.rb
class Season < ActiveRecord::Base
  validates :status, inclusion: { in: ['active', 'inactive'] }
end

app/models/team.rb
class Team < ActiveRecord::Base
  before_create :inactive_season

  has_many :match_results
  validates :name, presence: true, length: { minimum: 3 }, uniqueness: true

  def inactive_season
    raise 'Sezon jest już rozpoczęty.' if Season.find(1).status == 'active'
  end

  # include Comparable
  #
  # def <=>(other)
  #   self.score <=> other.score
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cache_buster
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include RoundsHelper
  include SeasonsHelper
  include TeamsHelper

  def set_cache_buster
    response.headers["Cache-Control"] = "no-store"
  end
end

app/controllers/match_results_controller.rb
class MatchResultsController < ApplicationController
  def update
    @round = Round.find(params[:round])
    @round_next = Round.find_by(id: params[:round].to_i + 1)
    @match_results = MatchResult.find(params[:end_round][:match_result].keys)
    if @match_results.each do |mr|
      mr.update(params[:end_round][:match_result][mr.id.to_s].permit(:scores))
    end
      @round.update_attributes(status: 'closed')
      @round_next.update_attributes(status: 'open') unless @round_next.blank?
      played_round(@round)
      flash[:success] = 'Zapisano wyniki meczów'
      if Round.active_rounds.blank?
        redirect_to seasons_path
      else
        redirect_to rounds_index_path
      end
    else
      flash[:error] = "Problem z zapisaniem wyników meczów"
      redirect_to :back
    end
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def index
    @rounds = Round.all
  end

  def show
    @round = Round.find(params[:id])
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  def index
    @rounds = Round.all
    @teams = Team.order(:place)
    sort_by_place
  end

  def new
    MatchResult.delete_all
    Match.delete_all
    Round.delete_all
    Team.delete_all
    Season.find(1).update(status: 'inactive')
    flash[:notice] = 'Przed Sezonem'
    redirect_to teams_path
  end

  def update
    if Team.count >= 4 && Team.count%2 == 0
      @season = Season.find(1)
      @season.update(status: params[:status])
      create_season
      flash[:notice] = 'Sezon został rozpoczęty'
      redirect_to rounds_index_path
    else
      redirect_to teams_path
      flash[:notice] = 'Brak wystarczającej liczby Drużyn, bądź liczba ich jest nieparzysta.'
    end
  end

  def index_classification
    @teams = Team.order(:place)
    sort_by_place
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :season_active

  def index
    @teams = Team.order(:id)
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      flash[:notice] = 'Dodano Drużynę.'
      redirect_to teams_path
    else
      flash.now[:notice] = 'Nie dodano Drużyny.'
      render 'new'
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])
    if @team.update(team_params)
      flash[:notice] = 'Zaktualizowano Drużynę.'
      redirect_to root_path
    else
      flash.now[:notice] = 'Nie zaktualizowano Drużyny.'
      render :edit
    end
  end

  def destroy
    @team = Team.find(params[:id])
    if @team.delete
      flash[:notice] = 'Usunięto Drużynę.'
      redirect_to :back
    else
      flash[:notice] = 'Wystąpił problem z usunięciem Drużyny.'
      redirect_to :back
    end
  end

  def team_params
    params.require(:team).permit(:name)
  end

  def season_active
    redirect_to rounds_index_path if Season.find(1).status == 'active'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/match_results_helper.rb
module MatchResultsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper

  def have_same_match?(team1, team2)
    array1 = []
    array2 = []
    team1.match_results.each do |mr|
      array1 << mr.match.id
    end
    team2.match_results.each do |mr|
      array2 << mr.match.id
    end
    array1.each do |array|
          return true if array2.include?(array)
    end
    false
  end

  def create_round(number)
    if number == 1
      @round = Round.create(status: 'open', number: number)
    else
      @round = Round.create(status: 'inaccessible', number: number)
    end
    @list = Team.all
    @list.each do |team|
      next if has_same_round?(team, @round.id)
      @list.each do |team2|
        next if team == team2
        next if has_same_round?(team2, @round.id)
        unless have_same_match?(team, team2)
         @match = Match.create(round_id: @round.id)
          MatchResult.create(match_id: @match.id, team_id: team.id )
          MatchResult.create(match_id: @match.id, team_id: team2.id )
          break
        end
      end
    end
  end

  def has_same_round?(team, round)
      team.match_results(true).each do |mr|
        if mr.match.round_id == round
          return true
        end
      end
    false
  end

  def played_round(round)
    round.matches.each do |match|
      max = 0
      min = 10000
      match.match_results.each do |mr|
       max = mr.scores if mr.scores > max
       min = mr.scores if mr.scores < min
      end
      match.match_results.each do |mr|
      if max == min
        mr.points = 1
      elsif mr.scores == max
        mr.points = 2
      else
        mr.scores == 0
        mr.points = 0
      end
      mr.team.update(score: mr.team.score + mr.points)
      end
    end
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
  def create_season
    sum_teams = Team.all.count
    sum_round = sum_teams - 1

    ActiveRecord::Base.connection.execute("truncate TABLE match_results")
    ActiveRecord::Base.connection.execute("truncate TABLE matches CASCADE")
    ActiveRecord::Base.connection.execute("truncate TABLE rounds CASCADE")
    (1..sum_round).each do |i|
        create_round(i)
    end
  end

end

app/helpers/teams_helper.rb
module TeamsHelper
  # def sort_by_place
  #   num = 1
  #     Team.all.sort { |team1, team2| team2.score <=> team1.score }.each do |team|
  #       @team = Team.all.to_a
  #       @team2 = Team.where(id: team.id)
  #       rmv_team = @team - @team2
  #       if rmv_team.each do |rmv|
  #         if rmv.score == team.score
  #         team.update(place: num)
  #         break
  #         end
  #       end
  #       end
  #       team.update(place: num)
  #       num += 1
  #     end
  # end

  def sort_by_place
    Team.all.to_a.group_by(&:score).to_a.sort_by(&:first).map(&:last).reverse.each_with_index { |t, index| t.each { |team| team.update(place: index + 1)}}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoccerManager</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>

<% flash.each do |key, value| %>
    <%= js add_gritter(value, flash[key], :image => key, :title => "Komunikat:", nodom_wrap: true) %>
<% end %>

</body>
</html>

app/views/rounds/_listing_match_results.html.erb
<% @round.matches.each do |match| %>
    <tr>
      <td><%= "Mecz nr #{match.id}" %></td>
      <% match.match_results.each do |mr| %>
          <td><%= mr.team.name %></td>

          <%= f.simple_fields_for mr, index: mr.id do |form| %>
              <td><%= form.input :scores, collection: 0..10, default: 0, label: false %>
              </td>
          <% end %>
      <% end %>
    </tr>
<% end %>

app/views/rounds/index.html.erb
<div class="jumbotron" style="text-align: center"><h2>SEZON ROZPOCZĘTY</h2></div>

<table class="table table-responsive">
  <tr>
    <th>Runda</th>
    <th>Status</th>
    <th>Wynik</th>
  </tr>
  <% @rounds.each do |round| %>
  <tr>
    <% if round.status == 'closed' %>
        <td><del><%= "Runda #{round.id}" %></del></td>
        <td><%= round.status %></td>
        <td>
        <% round.matches.each do |match| %>
            <% match.match_results.each_with_index do |mr, index| %>
                <% if index == 0 %>
                   <em><%= mr.team.name %></em> <strong><%= mr.scores %></strong>&nbsp;:
                <% else %>
                    <strong><%= mr.scores %></strong> <em><%= mr.team.name %></em>
                      <br>
                <% end %>
            <% end %>
        <% end %>
        </td>
    <% elsif round.status == 'open' %>
        <td><%= link_to "Runda #{round.id}", show_round_path(round) %></td>
        <td><%= round.status %></td>
        <td>-</td>
    <% else %>
        <td><%= "Runda #{round.id}" %></td>
        <td><%= round.status %></td>
        <td>-</td>
    <% end %>
  </tr>
  <% end %>
</table>

<%= link_to 'Klasyfikacja Drużyn', classification_path, class: 'btn btn-primary btn-large', style: 'float:right' %>

<% if Round.active_rounds.blank? && Round.count != 0 %>
    <p>Rozegrano wszystkie kolejki, przejdź do podsumowania.</p><br>
<%= link_to "Podsumowanie", seasons_path, class: 'btn btn-default' %>
<% end %>

app/views/rounds/show.html.erb
<%= simple_form_for :end_round, url: { action: :update, controller: 'match_results', round: params[:id] }, method: :patch do |f| %>
<table class="table table-responsive">
  <tr>
    <th>Mecz</th>
    <th>Drużyna 1</th>
    <th>Wynik dla Drużyny 1</th>
    <th>Drużyna 2</th>
    <th>Wynik dla Drużyny 2</th>
  </tr>

  <%= render 'listing_match_results', f: f %>

</table>
<%= f.button :submit, 'Zamknij Rundę', style: 'float:right', :class => 'btn btn-large btn-primary' %>
<% end %>

app/views/seasons/index.html.erb
<div class="jumbotron" style="text-align: center"><h2>TERMINARZ</h2></div>

<table class="table table-responsive table-hover">
  <tr>
    <th>Runda</th>
    <th>Status</th>
  </tr>
  <% @rounds.each do |round| %>
      <tr>
        <% if round.status == 'closed' %>
            <td><del><%= "Runda #{round.id}" %></del></td>
            <td><%= round.status %></td>
        <% elsif round.status == 'open' %>
            <td><%= link_to "Runda #{round.id}", show_round_path(round) %></td>
            <td><%= round.status %></td>
        <% else %>
            <td><%= "Runda #{round.id}" %></td>
            <td><%= round.status %></td>
        <% end %>
      </tr>
  <% end %>
</table>

<div class="jumbotron" style="margin-top: 100px; text-align: center"><h2>KLASYFIKACJA DRUŻYN</h2></div>
<table class="table table-responsive table-hover">
    <tr>
      <th>Miejsce</th>
      <th>Nazwa Drużyny</th>
      <th>Punkty</th>
    </tr>

    <% @teams.each do |team| %>
        <tr>
          <td><%= team.place %></td>
          <td><%= team.name %></td>
          <td><%= team.score %></td>
        </tr>
    <% end %>
</table>

<% if Round.active_rounds.blank? && Round.count != 0 %>
    <%= link_to 'Nowy Sezon', new_season_path, class: 'btn btn-large btn-danger' %>
<% end %>

app/views/seasons/index_classification.html.erb
<table class="table table-responsive table-hover">
  <tr>
    <th>Miejsce</th>
    <th>Nazwa Drużyny</th>
    <th>Punkty</th>
  </tr>

  <% @teams.each do |team| %>
  <tr>
    <td><%= team.place %></td>
    <td><%= team.name %></td>
    <td><%= team.score %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'Kolejki spotkań', rounds_index_path, class: 'btn btn-primary btn-large', style: 'float:right' %>

    <% if Round.active_rounds.blank? && Round.count != 0 %>
        <p>Rozegrano wszystkie kolejki, przejdź do podsumowania.</p><br>
        <%= link_to "Podsumowanie", seasons_path, class: 'btn btn-default' %>
        <% end %>